### ISSUE TITLE
Is this an updated version of textract?

### ISSUE THREAD

**Issue by dotnetCarpenter** [nosferatu500/textract#1]
My main issue with `textract` is the dependency of old package with security vulnerabilities. Is this a fork with those dependencies updated?

**Comment by nosferatu500** [comment]
Hi! Sorry for late answer.

Yes, I check deps for vulnerabilities almost every month.

**Comment by nosferatu500** [comment]
Updated with latest security vulnerabilities fixes. (v3.0.2)
